### ISSUE TITLE
Table rows does not have correct span size.

### ISSUE THREAD

**Issue by victorpierredev** [benjaminRomano/todo-manager#11]
Column are too small when I open

![bdtodo](https://cloud.githubusercontent.com/assets/4654583/13883188/b2259c0e-ecfe-11e5-9913-2d75b244f744.png)

Os: Elementary Os Freya (ubuntu 14.04).
Atom Theme: One Dark | Syntax Theme: One Dark
Atom version: 1.5.3

**Comment by benjaminRomano** [comment]
I pushed out a new version (v0.2.12). Are you still experiencing the bug?

**Comment by victorpierredev** [comment]
The problem has been solved, Thanks and great work :+1:
