### ISSUE TITLE
Q: How to change REGEX ?

### ISSUE THREAD

**Issue by X-Raym** [benjaminRomano/todo-manager#12]
Hi,

Where do I have to put the code the change/cretae my own REGEX ?

Thanks :)

**Comment by benjaminRomano** [comment]
Go to File > Config.  It should open up a config.cson file where you can put your own custom regexes.

**Comment by X-Raym** [comment]
Thanks !

I guess it doesn't cause I don't succeed to make the regex right then.

I am trying to make a list of all available function
`function FunctioName()`
Is it possible ? :)

**Comment by benjaminRomano** [comment]
Its probably possible with regexes, but I'm not an expert at regex so I don't know how you would go about making that.

**Comment by X-Raym** [comment]
Ok, it is a bit hard to test at the editor seems to have to be closed to take into account the changes made but maybe I will succeed.
thanks for the infos, and for your plugin ! Cheers !
