### ISSUE TITLE
Toolbar overriden by table

### ISSUE THREAD

**Issue by fische** [benjaminRomano/todo-manager#14]
Hi !
I'm using atom-material-ui theme and here's what I get when I open todo-manager :
![screenshot from 2016-05-20 10-25-47](https://cloud.githubusercontent.com/assets/6719270/15423839/460e8454-1e77-11e6-9ff7-e391cc0e8f5d.png)
Toolbar seems to be overriden by the table.
**Edit**: actually it seems that it is overriden in gulp-manager and linter-manager too. Is this issue related to bottom-dock ?

**Comment by benjaminRomano** [comment]
This is a problem with bottom-dock. 
I've opened an issue here https://github.com/benjaminRomano/bottom-dock/issues/13 and I'll take a look at it when I get a chance

I'm closing this one for now.
