### ISSUE TITLE
Relative paths 

### ISSUE THREAD

**Issue by laughedelic** [benjaminRomano/todo-manager#3]
Thanks for the great package! I've tried several similar plugins before and so far this one is the most convenient :+1:
It would be nice to show file paths relatively to the project (but with the project name in case there are several in one window) instead of absolute paths. It could be optional if you made it this way on purpose.

**Comment by benjaminRomano** [comment]
That's a good idea. I'll look into it.

**Comment by benjaminRomano** [comment]
Added this in https://github.com/benjaminRomano/todo-manager/commit/d2f096637f67668006503dc300c2b6c66f3b4918. 

I made it so that it shows relative paths for one project and then the project directory and relative path for many projects.

**Comment by laughedelic** [comment]
Thanks!
