### ISSUE TITLE
Problem with ignored paths

### ISSUE THREAD

**Issue by laughedelic** [benjaminRomano/todo-manager#5]
I want to add `*/docs/src/` to the `ignoredNames` setting, but it doesn't work. Actually whatever I try to add it doesn't have any effect on the output. Could you check this setting?

**Comment by benjaminRomano** [comment]
Fixed in https://github.com/benjaminRomano/todo-manager/commit/410ce6b3f72dcb1f9bb69ca430e17b41484b3839

**Comment by laughedelic** [comment]
I've updated, but the problem remains

**Comment by benjaminRomano** [comment]
So the problem is that to match against `docs/src/someFile.js` you would need to use this `**/docs/src/**`.  Also, my defaults and examples are using the incorrect format. I've fixed this in https://github.com/benjaminRomano/todo-manager/commit/cc837d2358d64d4827796af839224b0c4d46a6e6

**Comment by laughedelic** [comment]
thank you! this works :ok_hand:
